[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -Iinc
lib_deps = 
    adafruit/Adafruit VEML7700 Library@2.1.6
    adafruit/Adafruit BusIO@1.16.1
    knolleary/PubSubClient@2.8
