[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = "0s"
  hostname = "raspberrypi"
  omit_hostname = false

[[outputs.influxdb_v2]]
  urls = ["http://localhost:8086"]
  token = "sKpMfRnV1uconsMRdyxTRFWF-KnyT8DXxZrElm53T0hUYb9ENNb0-9Vt-r4WS013H65WBVKBnA6E09GxgxgwhA=="
  organization = "lab"
  bucket = "lux_sensors"
  timeout = "5s"

[[inputs.mqtt_consumer]]
  servers = ["tcp://localhost:1883"]
  topics = [
    "lab/lux/esp32_01/#"
  ]
  client_id = "telegraf_pi5_lux"
  qos = 0
  connection_timeout = "30s"
  persistent_session = false
  topic_tag = "topic"
  data_format = "value"
  data_type = "float"
  name_override = "luxometro"

[[processors.regex]]
  namepass = ["luxometro"]

  [[processors.regex.tags]]
    key = "topic"
    pattern = "^lab/lux/([^/]+)/([^/]+)/([^/]+)$"
    replacement = "${1}"
    result_key = "device"

  [[processors.regex.tags]]
    key = "topic"
    pattern = "^lab/lux/([^/]+)/([^/]+)/([^/]+)$"
    replacement = "${2}"
    result_key = "sensor"

  [[processors.regex.tags]]
    key = "topic"
    pattern = "^lab/lux/([^/]+)/([^/]+)/([^/]+)$"
    replacement = "${3}"
    result_key = "metric"
